#!/usr/bin/python

#
# gxparam.py	  Constants for config parameter names related to Base gxserver
# ----------
#
#
# $Source: /ext_hd/cvs/gx/gxparam.py,v $
# $Header: /ext_hd/cvs/gx/gxparam.py,v 1.8 2006/02/02 14:53:14 toucheje Exp $
#
#  Copyright (c) 2001-2006 Jean-Francois Touchette
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Library General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU Library General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  (The file "COPYING" or "LICENSE" in a directory above this source file
#  should contain a copy of the GNU Library General Public License text).
#  -------------------------------------------------------------------------
#
#
# ------------------------------------------------------------------------------
# 2002jan23,jft: first version
# 2002feb28,jft: added GXPARAM_INTERCEPT_DEFINITIONS, GXPARAM__FILTERS, etc.
# 2002apr03,jft: + GXPARAM_ACTIVE_QUEUE, GXPARAM_CUSTOM_INTERCEPT
# 2002apr07,jft: + GXPARAM_CUSTOM_REGPROCEXECPOOL_MAXRES
# 2002jun28,jft: + GXPARAM_MAX_WAIT_IN_DEST_QUEUE
# 2002nov27,jft: + GXPARAM_DEST_ROUTE_, GXPARAM_INITIAL_ROUTE
#		 - removed: GXPARAM_DEST_IP_ADDRESS, GXPARAM_DEST_PORT, GXPARAM_SERVER_LISTENPORT
# 2002jan24,jft: + GXPARAM_QUEUE_DUMP_DIR
# 2003jul23,jft: + GXPARAM_TRACE_INIT, GXPARAM_TRACE_
# 2004jul21,jft: + GXPARAM__POST_GETQ_FUNCTION  GXPARAM__PROCESS_DUMP_QUEUE_FUNCTION
#		 + GXPARAM__POST_PUTQ_FUNCTION  GXPARAM__POST_GETQ_ACTIVE_QUEUE_FUNCTION
#		 + GXPARAM__POST_EXEC_RPC_FUNCTION
# 2004jul23,jft: + GXPARAM__DATA_PATH
# 2004jul30,jft: + GXPARAM__EXTRA_DATA_LIST
# 2004nov06,jft: + GXPARAM__INTERCEPT_RETURN_STATUS
# 2005sep30,jft: + GXPARAM_MULTI  GXPARAM__MULTI_LIST
# 2005dec14,jft: + GXPARAM_NOTIFY_UDP
# 2006jan29,jft: + GXPARAM_AUDIT_USERID_PARAM_NAME
#		 + GXPARAM__STORAGE   -- new queue attribute
#		 + GXPARAM_PERSISTENT
#		 + GXPARAM_IN_MEMORY
# 2006jan30,jft: + GXPARAM_PERSISTENT_QUEUES_DIR
#		 + GXPARAM_INITIAL_RPC_GATE
#

GXPARAM_AUDIT_USERID_PARAM_NAME	= "AUDIT_USERID_PARAM_NAME"

GXPARAM_INITIAL_RPC_GATE	= "INITIAL_RPC_GATE"


# params for trace levels to be set at start-up time:
#
GXPARAM_TRACE_INIT		= "TRACE_INIT"
GXPARAM_TRACE_			= "TRACE_"


# Params about incoming sockets and clients (logins):
#
GXPARAM_MAX_CLIENTS_SOCKETS	= "MAX_CLIENTS_SOCKETS"
GXPARAM_MAX_CLT_CONNECTIONS	= "MAX_CLT_CONNECTIONS"

GXPARAM_CLIENT_RECV_TIMEOUT	= "CLIENT_RECV_TIMEOUT"
GXPARAM_CLIENT_SEND_TIMEOUT	= "CLIENT_SEND_TIMEOUT"


# Params about RPC execution and "destinations":
#
GXPARAM_RPC_TIMEOUT		= "RPC_TIMEOUT"
GXPARAM_MAX_WAIT_IN_DEST_QUEUE	= "MAX_WAIT_IN_DEST_QUEUE"

GXPARAM_DEST_LOGIN_PROC		= "DEST_LOGIN_PROC"
GXPARAM_DEST_SEND_TIMEOUT	= "DEST_SEND_TIMEOUT"

GXPARAM_DEST_ROUTE_		= "DEST_ROUTE_"		# actual param must be suffixed by A, B, C, D or E
GXPARAM_INITIAL_ROUTE		= "INITIAL_ROUTE"

GXPARAM_DEFAULT_DESTINATION	= "DEFAULT_DESTINATION"
GXPARAM_DESTINATIONS		= "DESTINATIONS"
GXPARAM_RPC_FOR_DEST_		= "RPC_FOR_DEST_"

GXPARAM_MAX_CONNECTIONS		= "MAX_CONNECTIONS"
GXPARAM_USR_ID			= "USR_ID"
GXPARAM_USR_PWD_FILE		= "USR_PWD_FILE"


GXPARAM_RPCS_ALWAYS_BLOCKED	= "RPCS_ALWAYS_BLOCKED"


# Parameters required by gxserver.py :
#
GXPARAM_CALLPARSERSPOOL_MAXRES	= "CALLPARSERSPOOL_MAXRES"
GXPARAM_REGPROCEXECPOOL_MAXRES	= "REGPROCEXECPOOL_MAXRES"
GXPARAM_CUSTOM_REGPROCEXECPOOL_MAXRES = "CUSTOM_REGPROCEXECPOOL_MAXRES"



#
# New parameters to simplify the config file:
#
GXPARAM_PATH_OF_PASSWORD_FILES	= "PATH_OF_PASSWORD_FILES"

GXPARAM_PATH_OF_UNAVAILABITY_MESSAGES = "PATH_OF_UNAVAILABITY_MESSAGES"

#
# new parameters used by gxintercept.py :
#
GXPARAM_QUEUE_DUMP_DIR		= "QUEUE_DUMP_DIR"

GXPARAM_PERSISTENT_QUEUES_DIR	= "PERSISTENT_QUEUES_DIR"

GXPARAM_INTERCEPT_DEFINITIONS	= "INTERCEPT_DEFINITIONS"
GXPARAM__FILTERS		= "_FILTERS"
GXPARAM__INTERCEPT_RPCS		= "_INTERCEPT_RPCS"
GXPARAM__PARAM			= "_PARAMS"
GXPARAM__COLUMNS		= "_COLUMNS"
GXPARAM__TRANS_ID		= "_TRANS_ID"
GXPARAM__TYPE			= "_TYPE"
GXPARAM_MULTI				= "MULTI"
GXPARAM_NOTIFY_UDP			= "NOTIFY_UDP"
GXPARAM_QUEUE				= "QUEUE"
GXPARAM_QUEUE_SWITCH			= "QUEUE_SWITCH"
GXPARAM_ACTIVE_QUEUE			= "ACTIVE_QUEUE"
GXPARAM_CUSTOM_INTERCEPT		= "CUSTOM_INTERCEPT"
GXPARAM_TO_TEXT_FILE			= "TO_TEXT_FILE"	# not used

# params for type == MULTI :
#
GXPARAM__MULTI_LIST			= "_MULTI_LIST"

# params for type == QUEUE_SWITCH:
#
GXPARAM__QUEUE_1			= "_QUEUE_1"
GXPARAM__QUEUE_2			= "_QUEUE_2"

# params for type == CUSTOM_INTERCEPT :
#
GXPARAM__PARAM_FUNCTION		= "_PARAM_FUNCTION"
GXPARAM__PARAM_FUNCTION_ARGS	= "_PARAM_FUNCTION_ARGS"
GXPARAM__RESULT_FUNCTION	= "_RESULT_FUNCTION"
GXPARAM__RESULT_FUNCTION_ARGS	= "_RESULT_FUNCTION_ARGS"
GXPARAM__INTERCEPT_RETURN_STATUS = "_INTERCEPT_RETURN_STATUS"

# params for type == QUEUE :
#
GXPARAM__Q_MAX			= "_Q_MAX"
GXPARAM__MAX_ROWS_IN_GET	= "_MAX_ROWS_IN_GET"
GXPARAM__NOTIFY_UDP_ADDRESS	= "_NOTIFY_UDP_ADDRESS"
GXPARAM__NOTIFY_INTERVAL	= "_NOTIFY_INTERVAL"
GXPARAM__LOG_MARKER_FAILED	= "_LOG_MARKER_FAILED"
GXPARAM__LOG_MARKER		= "_LOG_MARKER"
GXPARAM__OPEN_AT_INIT		= "_OPEN_AT_INIT"
GXPARAM__QUEUE_CLOSED_MSG	= "_QUEUE_CLOSED_MSG"
GXPARAM__QUEUE_FULL_MSG		= "_QUEUE_FULL_MSG"

GXPARAM__STORAGE		= "_STORAGE"		# for QUEUE or ACTIVE_QUEUE
GXPARAM_PERSISTENT			= "PERSISTENT"
GXPARAM_IN_MEMORY			= "IN_MEMORY"

GXPARAM__POST_GETQ_FUNCTION		 = "_POST_GETQ_FUNCTION"
GXPARAM__PROCESS_DUMP_QUEUE_FUNCTION	 = "_PROCESS_DUMP_QUEUE_FUNCTION"
GXPARAM__DATA_PATH			 = "_DATA_PATH"
GXPARAM__EXTRA_DATA_LIST		 = "_EXTRA_DATA_LIST"


# params for type == ACTIVE_QUEUE :
#
GXPARAM__POST_PUTQ_FUNCTION		 = "_POST_PUTQ_FUNCTION"
GXPARAM__POST_GETQ_ACTIVE_QUEUE_FUNCTION = "_POST_GETQ_ACTIVE_QUEUE_FUNCTION"
GXPARAM__POST_EXEC_RPC_FUNCTION		 = "_POST_EXEC_RPC_FUNCTION"

GXPARAM__RPC_NAME		= "_RPC_NAME"



# 
# GXPARAM_ which used to be CIGPARAM_
#
# (Originally from lbospar1.h, 1997oct24)
#

GXPARAM_INITIAL_GATE_STATUS	= "INITIAL_GATE_STATUS"
GXPARAM_VAL_GATE_CLOSED		= "closed"

GXPARAM_AUTHENTICATION_RPC	= "AUTHENTICATION_RPC"


GXPARAM_WHO_HAS_LANG_PERM	= "WHO_HAS_LANG_PERM"
GXPARAM_WHO_HAS_OPER_PERM	= "WHO_HAS_OPER_PERM"
GXPARAM_WHO_HAS_STATS_PERM	= "WHO_HAS_STATS_PERM"
GXPARAM_WHO_HAS_SHUTDOWN_PERM	= "WHO_HAS_SHUTDOWN_PERM"

GXPARAM_PWD_FILE_OF_		= "PWD_FILE_OF_"


#
# params for special hours operations of CIG:
#
GXPARAM_GROUPS_OF_RPC			= "GROUPS_OF_RPC"
GXPARAM_RPCS_OF_GROUP_			= "RPCS_OF_GROUP_"
GXPARAM_MSG_FILE_FOR_BLOCKED_GROUP_	= "MSG_FILE_FOR_BLOCKED_GROUP_"



#
# Parameter related to "getfile" operator command:
#
GXPARAM_ALLOW_GETFILE_ON	= "ALLOW_GETFILE_ON"



## BEGIN Not used yet (2002june28):
##
## GXPARAM_ROUTES			= "ROUTES"
## GXPARAM_ROUTE_INFIX		= "_ROUTE_"
## GXPARAM_CHECK_ROUTE_RPC_NAME	= "CHECK_ROUTE_RPC_NAME"
#
## END Not used yet (2002june28):


#
# end of gxparam.py
# 

