/* errutl_1.c
 * ----------
 *
 *
 *  Copyright (c) 1994-2003 Jean-Francois Touchette
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  (The file "COPYING" or "LICENSE" in a directory above this source file
 *  should contain a copy of the GNU Library General Public License text).
 *  -------------------------------------------------------------------------
 *
 * $Source: /ext_hd/cvs/ct10api/errutl_1.c,v $
 * $Header: /ext_hd/cvs/ct10api/errutl_1.c,v 1.9 2005/06/01 20:04:42 toucheje Exp $
 *
 *
 * Functions prefix:	errutl_
 * 
 * This file contains Utility functions used by the generic Error handlers
 * functions (those in ct_errh1.c)
 *
 * -------------------------------------------------------------------------
 * Versions:
 * 1994oct20,jft: first version
 * 1997feb18,deb: Added conditional include for Windows NT port.
 * 2005jun01,jft: to simplify porting, added: #if !defined(CS_INT)  #include "cstypes.h"  #endif
 *                same for CS_MAX_MSG and "cspublic.h"
 */

#ifdef WIN32		/* for port of CT10API to Windows NT */
#include "ntunixfn.h"
#include "lbos_def.h"	/* all LBOS_xxxx defines		*/
#include "alogelvl.h"	/* ALOG_xxx defines			*/
#else
#include "os10stdf.h"	/* standard #includes and #defines for OS 10.0 */
#endif

#if !defined(CS_INT)
#include "cstypes.h"
#endif

#if !defined(CS_MAX_MSG)
#include "cspublic.h"
#endif

#include "errutl_1.h"	/* public functions prototypes for this module */



/* --------------------------------------- Private Defines: */



/* --------------------------------------- Private (static) variables: */


/* ------------------------------------------------ Public functions: */

int errutl_severity_to_alog_err_level(CS_INT severity)
{
	if (severity >= 17) {		/* 17..26 serious remote error */
		return (ALOG_ERROR);
	}	

	if (severity > 10) {		/* 11..16 User errors */
		return (ALOG_WARN);
	}

	if (severity == 0) {		/* Informational msg */
		/*
		 * This test for == 0 is not in the following
		 * switch() because it would conflict with 
		 * CS_SV_INFORM... which is also 0.
		 */
		return (ALOG_INFO);
	}

	/*
	 * The CS_SV_INFORM and other CS_SV_xxxx constants are defined in
	 * "cstypes.h"
	 * These constant are described in "Open Client Client-Library/C
	 * Reference Manual" (10.0) in section "CS_CLIENTMSG Structure",
	 * Table 2-10, page 2-41 (section 2, page 41).
	 */
	switch (severity) {
	 /* 0, 2, 10: */
	 case 10:			/* SQL Server Informational messages */
	 case CS_SV_INFORM:		/* CT-Lib Informational messages  */
	 case CS_SV_RETRY_FAIL:		/* CT-Lib Fail but can be retried */
		return (ALOG_INFO);

	 /* 1, 3, 5: */
	 case CS_SV_API_FAIL:		/* CT-Lib bad API call		     */
	 case CS_SV_RESOURCE_FAIL:	/* CT-Lib typicallly: malloc fail    */
	 case CS_SV_COMM_FAIL:		/* CT-Lib communication channel fail */
		return (ALOG_WARN);

	 /* 4, 6, 7: */
	 case CS_SV_CONFIG_FAIL:	/* CT-Lib Sybase config error found */
	 case CS_SV_INTERNAL_FAIL:	/* CT-Lib internal CT-Lib error	    */
	 case CS_SV_FATAL:		/* CT-Lib serious error: all server */
		return (ALOG_ERROR);	/* 	  connections are unusable  */

	 /* 8, 9: */
	 default:			/* 8,9: generated by our Open Server */
		break;
	}	 
	return (ALOG_WARN);

} /* end of errutl_severity_to_alog_err_level() */






void errutl_terminate_msg_text(CS_CHAR *p_text, CS_INT text_len)
{
	if (p_text == NULL) {
		return;
	}
		/* Null terminate message. */
	switch ((int)(text_len))	{
	case CS_NULLTERM:		/* Message already NULL terminated. */
		break;
	case CS_UNUSED:
	case 0:				/* No message specified. */
		p_text[0] = '\0';
		break;
	default:
		if(text_len >= CS_MAX_MSG) {
			text_len = (CS_MAX_MSG - 1);
		}
		p_text[text_len] = '\0';
		break;
	}
	return;

} /* end of errutl_terminate_msg_text() */


/* ---------------------------------------- end of errutl_1.c ------------ */

