/* Generated by JavaSQLTypes.java
 * from java.sql.Types
 * 2001aug30
 */
#define JAVA_SQL_BIGINT		-5
#define JAVA_SQL_BINARY		-2
#define JAVA_SQL_BIT		-7
#define JAVA_SQL_CHAR		1
#define JAVA_SQL_DATE		91
#define JAVA_SQL_DECIMAL		3
#define JAVA_SQL_DOUBLE		8
#define JAVA_SQL_FLOAT		6
#define JAVA_SQL_INTEGER		4
#define JAVA_SQL_LONGVARBINARY		-4
#define JAVA_SQL_LONGVARCHAR		-1
#define JAVA_SQL_NULL		0
#define JAVA_SQL_NUMERIC		2
#define JAVA_SQL_OTHER		1111
#define JAVA_SQL_REAL		7
#define JAVA_SQL_SMALLINT		5
#define JAVA_SQL_TIME		92
#define JAVA_SQL_TIMESTAMP		93
#define JAVA_SQL_TINYINT		-6
#define JAVA_SQL_VARBINARY		-3
#define JAVA_SQL_VARCHAR		12
