/**
 * JavaSQLTypes.java 
 * -----------------
 *
 *
 *  Copyright (c) 2001 Jean-Francois Touchette
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  (The file "COPYING" or "LICENSE" in a directory above this source file
 *  should contain a copy of the GNU Lesser General Public License text).
 *  -------------------------------------------------------------------------
 *
 * $Source: /ext_hd/cvs/xmltp/JavaSQLTypes.java,v $
 * $Header: /ext_hd/cvs/xmltp/JavaSQLTypes.java,v 1.3 2004/10/13 18:23:42 blanchjj Exp $
 *
 * This small Java program writes a bunch of C define's for each of the values 
 * of the java.sql.Types constants (public static final "variables" in Java's jargon).
 *
 * 2001aug30,jft
 */
import java.io.*;
import java.sql.Types;

public class JavaSQLTypes {

public JavaSQLTypes() 
{
 }

public static void main (String args[]) throws Exception 
{
	System.out.println ("/* Generated by JavaSQLTypes.java");
	System.out.println (" * from java.sql.Types");
	System.out.println (" * 2001aug30");
	System.out.println (" */");
	display(java.sql.Types.BIGINT,		"BIGINT");
	display(java.sql.Types.BINARY,		"BINARY");
	display(java.sql.Types.BIT, 		"BIT");
	display(java.sql.Types.CHAR, 		"CHAR");
	display(java.sql.Types.DATE,	 	"DATE");
	display(java.sql.Types.DECIMAL, 	"DECIMAL");
	display(java.sql.Types.DOUBLE, 	"DOUBLE");
	display(java.sql.Types.FLOAT, 		"FLOAT");
	display(java.sql.Types.INTEGER, 	"INTEGER");
	display(java.sql.Types.LONGVARBINARY,	"LONGVARBINARY");
	display(java.sql.Types.LONGVARCHAR, 	"LONGVARCHAR");
	display(java.sql.Types.NULL, 		"NULL");
	display(java.sql.Types.NUMERIC, 	"NUMERIC");
	display(java.sql.Types.OTHER, 		"OTHER");
	display(java.sql.Types.REAL, 		"REAL");
	display(java.sql.Types.SMALLINT, 	"SMALLINT");
	display(java.sql.Types.TIME, 		"TIME");
	display(java.sql.Types.TIMESTAMP, 	"TIMESTAMP");
	display(java.sql.Types.TINYINT, 	"TINYINT");
	display(java.sql.Types.VARBINARY, 	"VARBINARY");
	display(java.sql.Types.VARCHAR, 	"VARCHAR");
}


public static void display(int val, String s) 
 {
	System.out.println ("#define JAVA_SQL_" + s + "\t\t" + val);
 }

} 

/* -------------------- EOF ----------------------- */
